### ISSUE TITLE
dropdown not working with bootstrap 5

### ISSUE THREAD

**Issue by GhislainL** [LazZiya/XLocalizer.DB.UI#5]
Hi @LazZiya 

the dropdown component syntax has changed between bootstrap 4 and 5.
Consequently dropdown menu do not work anymore.

I fixed it in a fork (https://github.com/GhislainL/XLocalizer.DB.UI).
But doing so break the retrocompatibility. 
How can we integrate the bootstrap 5's fix without breaking retrocompatiblity with bootstrap 4 ?

Regards,

Ghislain

**Comment by LazZiya** [comment]
Hi @GhislainL 

Fix published with [v1.1.0](https://github.com/LazZiya/XLocalizer.DB.UI/releases/tag/v1.1.0).

Just use below URL's according to your BS version:

````
// Bootstrap 4
https://localhost:44311/XLocalizer/Cultures
https://localhost:44311/XLocalizer/Resources

// Bootstrap5
https://localhost:44311/XLocalizerBS5/Cultures
https://localhost:44311/XLocalizerBS5/Resources
````
